server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  config:
    import: configserver:http://localhost:8888

#currency-exchange-service:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
